spring.application.name: web-service
eureka.client.serviceUrl.defaultZone: http://192.168.3.142:8881/eureka/
feign.hystrix.enabled: true
server.port: 8884
server.contextPath: /web
ribbon.ReadTimeout: 50000
ribbon.ConnectTimeout: 50000
jdbc.driverClassName: com.mysql.jdbc.Driver
jdbc.url: jdbc:mysql://192.168.3.133:3306/bh-demo-server?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
jdbc.username: root
jdbc.password: root
jdbc.initialSize: 1
jdbc.maxActive: 10
jdbc.minIdle: 10
jdbc.validationQuery: select '1'
spring.redis.database: 0
spring.redis.timeout: 0
spring.redis.host: 192.168.3.128
spring.redis.port: 6379
spring.redis.password: redis123
spring.redis.pool.max-active: 400
spring.redis.pool.max-wait: -1
spring.redis.pool. max-idle: 50
spring.redis.pool. min-idle: 0
upload.file.url: 192.168.3.141
upload.file.port: 21
upload.file.ftp.username: ftpuser
upload.file.ftp.password: ftpuser
upload.file.ftp.path: /home/ftpuser/img/
zookeeper.hosts: 192.168.3.128:2181
metadata.broker.list: 192.168.3.128:9092
serializer.class: kafka.serializer.StringEncoder
key.serializer.class: kafka.serializer.StringEncoder
buffer.memory: 67108864
batch.size: 131072
linger.ms: 100
max.request.size: 10485760
retries: 10
retry.backoff.ms: 500
kafka.topic: bh-business-topic
eureka.instance.lease-expiration-duration-in-seconds: 15
eureka.instance.lease-renewal-interval-in-seconds: 5
eureka.client.registryFetchIntervalSeconds: 5
ribbon.ServerListRefreshInterval: 1000
eureka.instance.preferIpAddress: true
eureka.server.enable-self-preservation: false
appoint.statistics.ip: 192.168.3.128
spring.cloud.alibaba.seata.tx-service-group: my_test_tx_group
logging.level.org.springframework.cloud.alibaba.seata.web: debug
logging.level.io.seata: debug
